name: Test Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test-matrix:

    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - run: mkdir -p path/to/artifact
      - run: echo hello1 > path/to/artifact/world1.txt
      - run: echo hello2 > path/to/artifact/world2.txt

      - uses: kittaakos/upload-artifact-as-is
        with:
          path: path/to/artifact/
