name: Test Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test-matrix:

    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn
